In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dialysis_Facility_Compare_-_Listing_by_Facility.csv')

In [3]:
df.head()

,Provider Number,Network,Facility Name,Five Star Date,Five Star,Five Star Data Availability Code,Address Line 1,Address Line 2,City,State,...,95% C.I. (lower limit) for SWR,Number of patients in this facility for SWR,Standardized First Kidney Transplant Waitlist Ratio,PPPW category text,Patient prevalent transplant waitlist data availability code,95% C.I. (upper limit) for PPPW,95% C.I. (lower limit) for PPPW,Number of patients for PPPW,Percentage of Prevalent Patients Waitlisted,Location
0,42592,13,DCI - LITTLE ROCK RENAL SERVICES LLC,01/01/2015 - 12/31/2018,2,1,1910 JOHN BARROW RD,NaN,LITTLE ROCK,AR,...,.12,56,.45,As Expected,1,22.8,3.4,100,9.2,POINT (-92.372456 34.73624)
1,52761,18,DAVITA-PREMIER DIALYSIS CENTER,01/01/2015 - 12/31/2018,3,1,7612 ATLANTIC AVENUE,NaN,CUDAHY,CA,...,.2,105,.53,As Expected,1,32.1,11.8,209,20.1,POINT (-118.187206 33.966829)
2,72549,1,WALLINGFORD DIALYSIS CARE LLC,01/01/2015 - 12/31/2018,5,1,720 N MAIN STREET EXT,SUITE 3,WALLINGFORD,CT,...,Not Available,12,Not Available,As Expected,1,74.5,10.1,24,36.4,POINT (-72.809521 41.472838)
3,82524,4,"DSI LAUREL DIALYSIS, LLC",01/01/2015 - 12/31/2018,4,1,LAUREL SQUARE SHOPPING CENTER,"30214 SUSSEX HIGHWAY, UNIT #4",LAUREL,DE,...,Not Available,8,Not Available,As Expected,1,74.2,.2,19,7.4,NaN
4,82527,4,"FRESENIUS MEDICAL CARE SOUTHERN DELAWARE, LLC",01/01/2015 - 12/31/2018,5,1,9115 ANTIQUE ALLEY,NaN,BRIDGEVILLE,DE,...,Not Available,1,Not Available,As Expected,1,48.4,2.8,44,14.2,POINT (-75.592475 38.735365)

In [4]:
df.tail()

,Provider Number,Network,Facility Name,Five Star Date,Five Star,Five Star Data Availability Code,Address Line 1,Address Line 2,City,State,...,95% C.I. (lower limit) for SWR,Number of patients in this facility for SWR,Standardized First Kidney Transplant Waitlist Ratio,PPPW category text,Patient prevalent transplant waitlist data availability code,95% C.I. (upper limit) for PPPW,95% C.I. (lower limit) for PPPW,Number of patients for PPPW,Percentage of Prevalent Patients Waitlisted,Location
7621,442666,8,DAVITA TENNESSEE VALLEY DIALYSIS CENTER,01/01/2015 - 12/31/2018,4,1,107 WOODLAWN DR,SUITE 100,JOHNSON CITY,TN,...,.01,39,.25,As Expected,1,33.1,2.1,76,9.5,POINT (-82.398053 36.307557)
7622,522598,11,DAVITA CAPITOL COURT DIALYSIS,01/01/2015 - 12/31/2018,3,1,4176 N 56TH ST,NaN,MILWAUKEE,WI,...,.05,52,.38,As Expected,1,32.6,5.2,82,14,POINT (-87.982914 43.093799)
7623,552873,18,DAVITA BRISTOL DIALYSIS,01/01/2015 - 12/31/2018,Not Available,258,1232 S BRISTOL ST,NaN,SANTA ANA,CA,...,Not Available,Not Available,Not Available,Not Available,258,Not Available,Not Available,Not Available,Not Available,POINT (-117.885172 33.731441)
7624,682558,7,FMC - WAUCHULA,01/01/2015 - 12/31/2018,4,1,457 CARLTON ST,NaN,WAUCHULA,FL,...,Not Available,22,Not Available,As Expected,1,35.4,1.9,56,9.2,POINT (-81.815351 27.536488)
7625,522548,11,DAVITA WEST APPLETON DIALYSIS,01/01/2015 - 12/31/2018,3,1,"10130 W APPLETON AVE, SUITE 500",NaN,MILWAUKEE,WI,...,.41,41,1.27,As Expected,1,36.9,7.1,92,17.4,POINT (-88.038798 43.12228)

In [5]:
df.shape

(7626, 119)

In [6]:
for col in df.columns: 
    print(col)

Provider Number
Network
Facility Name
Five Star Date
Five Star
Five Star Data Availability Code
Address Line 1
Address Line 2
City
State
Zip
County
Phone Number
Profit or Non-Profit
Chain Owned
Chain Organization
Late Shift
# of Dialysis Stations
Offers in-center hemodialysis
Offers peritoneal dialysis
Offers home hemodialysis training
Certification or Recertification Date
Claims Date
CROWNWeb Date
STrR Date
Percentage of Medicare patients with Hgb<10 g/dL
HGB<10 data availability code
Percentage of Medicare patients with Hgb>12 g/dL
Hgb > 12 data availability code
Number of Dialysis Patients with Hgb data
Patient Transfusion data availability Code
Patient Transfusion category text
Number of patients included in the transfusion summary
Percent of Adult HD patients with Kt/V >= 1.2
Adult HD Kt/V data availability code
Percentage of Adult PD PTS with Kt/V >= 1.7
Adult PD Kt/V Data Availability Code
Percentage of Pediatric HD patients with Kt/V >= 1.2
Pediatric HD Kt/V Data Availability Code
Number of Adult HD patients with Kt/V data
Number of Adult HD patient-months with Kt/V data
Number of Adult PD patients with Kt/V data
Number of Adult PD patient-months with Kt/V data
Number of Pediatric HD patients with Kt/V data
Number of Pediatric HD patient-months with Kt/V data
Hypercalcemia Data Availability Code
Number of patients in hypercalcemia summary
Number of patient-months in hypercalcemia summary
Percentage of Adult patients with hypercalcemia (serum calcium greater than 10.2 mg/dL)
Number of patients in Serum phosphorus summary
Number of patient-months in Serum phosphorus summary
Serum phosphorus Data Availability Code
Percentage of Adult patients with serum phosphorus less than 3.5 mg/dL
Percentage of Adult patients with serum phosphorus between 3.5-4.5 mg/dL
Percentage of Adult patients with serum phosphorus between 4.6-5.5 mg/dL
Percentage of Adult patients with serum phosphorus between 5.6-7.0 mg/dL
Percentage of Adult patients with serum phosphorus greater than 7.0 mg/dL
SHR Date
SRR Date
SMR Date
Patient Hospitalization category text
Patient Hospitalization data availability Code
Patient Hospital Readmission Category
Patient Hospital Readmission data availability Code
Patient Survival Category Text
Patient Survival data availability code
Number of patients included in hospitalization summary
Number of hospitalizations included in hospital readmission summary
Number of patients included in survival summary
Mortality Rate (Facility)
Mortality Rate: Upper Confidence Limit (97.5%)
Mortality Rate: Lower Confidence Limit (2.5%)
Readmission Rate (Facility)
Readmission Rate: Upper Confidence Limit (97.5%)
Readmission Rate: Lower Confidence Limit (2.5%)
Hospitalization Rate (Facility)
Hospitalization Rate: Upper Confidence Limit (97.5%)
Hospitalization Rate: Lower Confidence Limit (2.5%)
Number of pediatric PD patients with Kt/V data
Pediatric PD Kt/V Data Availability Code
Number of pediatric PD patient-months with KT/V data
Percentage of pediatric PD patients with Kt/V>=1.8
SIR Date
Patient Infection Data Availability Code
Patient Infection category text
Standard Infection Ratio
SIR: Upper Confidence Limit (97.5%)
SIR: Lower Confidence Limit (2.5%)
Transfusion Rate (Facility)
Transfusion Rate: Upper Confidence Limit (97.5%)
Transfusion Rate: Lower Confidence Limit (2.5%)
Fistula data availability code
Fistula Category Text
Number of Patients included in fistula summary
Fistula Rate (Facility)
Fistula Rate: Upper Confidence Limit (97.5%)
Fistula Rate: Lower Confidence Limit (2.5%)
Number of patients in long term catheter summary
Number of patient months in long term catheter summary
Long term catheter Data Availability Code
Percentage of Adult patients with long term catheter in use
Number of patients in nPCR summary
Number of patient-months in nPCR summary
nPCR Data Availability Code
Percentage of pediatric HD patients with nPCR
DATE_SWR
SWR category text
Patient transplant waitlist data availability code
95% C.I. (upper limit) for SWR
95% C.I. (lower limit) for SWR
Number of patients in this facility for SWR
Standardized First Kidney Transplant Waitlist Ratio
PPPW category text
Patient prevalent transplant waitlist data availability code
95% C.I. (upper limit) for PPPW
95% C.I. (lower limit) for PPPW
Number of patients for PPPW
Percentage of Prevalent Patients Waitlisted
Location

In [35]:
df.iloc[:, :60].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7626 entries, 0 to 7625
Data columns (total 60 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Provider Number                                                                          7626 non-null   int64
 1   Network                                                                                  7626 non-null   int64
 2   Facility Name                                                                            7626 non-null   object
 3   Five Star Date                                                                           7626 non-null   object
 4   Five Star                                                                                7626 non-null   object
 5   Five Star Data Availability Code                                                         7626 non-null   int64
 6   Address Line 1                                                                           7626 non-null   object
 7   Address Line 2                                                                           1087 non-null   object
 8   City                                                                                     7626 non-null   object
 9   State                                                                                    7626 non-null   object
 10  Zip                                                                                      7626 non-null   int64
 11  County                                                                                   7626 non-null   object
 12  Phone Number                                                                             7626 non-null   object
 13  Profit or Non-Profit                                                                     7626 non-null   object
 14  Chain Owned                                                                              7626 non-null   object
 15  Chain Organization                                                                       7625 non-null   object
 16  Late Shift                                                                               7626 non-null   int64
 17  # of Dialysis Stations                                                                   7626 non-null   int64
 18  Offers in-center hemodialysis                                                            7626 non-null   int64
 19  Offers peritoneal dialysis                                                               7626 non-null   int64
 20  Offers home hemodialysis training                                                        7626 non-null   int64
 21  Certification or Recertification Date                                                    7626 non-null   object
 22  Claims Date                                                                              7626 non-null   object
 23  CROWNWeb Date                                                                            7626 non-null   object
 24  STrR Date                                                                                7626 non-null   object
 25  Percentage of Medicare patients with Hgb<10 g/dL                                         7626 non-null   object
 26  HGB<10 data availability code                                                            7626 non-null   int64
 27  Percentage of Medicare patients with Hgb>12 g/dL                                         7626 non-null   object
 28  Hgb > 12 data availability code                                                          7626 non-null   int64
 29  Number of Dialysis Patients with Hgb data                                                7626 non-null   object
 30  Patient Transfusion data availability Code                                               7626 non-null   int64
 31  Patient Transfusion category text                                                        7626 non-null   object
 32  Number of patients included in the transfusion summary                                   7626 non-null   object
 33  Percent of Adult HD patients with Kt/V >= 1.2                                            7626 non-null   object
 34  Adult HD Kt/V data availability code                                                     7626 non-null   int64
 35  Percentage of Adult PD PTS with Kt/V >= 1.7                                              7626 non-null   object
 36  Adult PD Kt/V Data Availability Code                                                     7626 non-null   int64
 37  Percentage of Pediatric HD patients with Kt/V >= 1.2                                     7626 non-null   object
 38  Pediatric HD Kt/V Data Availability Code                                                 7626 non-null   int64
 39  Number of Adult HD patients with Kt/V data                                               7626 non-null   object
 40  Number of Adult HD patient-months with Kt/V data                                         7626 non-null   object
 41  Number of Adult PD patients with Kt/V data                                               7626 non-null   object
 42  Number of Adult PD patient-months with Kt/V data                                         7626 non-null   object
 43  Number of Pediatric HD patients with Kt/V data                                           7626 non-null   object
 44  Number of Pediatric HD patient-months with Kt/V data                                     7626 non-null   object
 45  Hypercalcemia Data Availability Code                                                     7626 non-null   int64
 46  Number of patients in hypercalcemia summary                                              7626 non-null   object
 47  Number of patient-months in hypercalcemia summary                                        7626 non-null   object
 48  Percentage of Adult patients with hypercalcemia (serum calcium greater than 10.2 mg/dL)  7626 non-null   object
 49  Number of patients in Serum phosphorus summary                                           7626 non-null   object
 50  Number of patient-months in Serum phosphorus summary                                     7626 non-null   object
 51  Serum phosphorus Data Availability Code                                                  7626 non-null   int64
 52  Percentage of Adult patients with serum phosphorus less than 3.5 mg/dL                   7626 non-null   object
 53  Percentage of Adult patients with serum phosphorus between 3.5-4.5 mg/dL                 7626 non-null   object
 54  Percentage of Adult patients with serum phosphorus between 4.6-5.5 mg/dL                 7626 non-null   object
 55  Percentage of Adult patients with serum phosphorus between 5.6-7.0 mg/dL                 7626 non-null   object
 56  Percentage of Adult patients with serum phosphorus greater than 7.0 mg/dL                7626 non-null   object
 57  SHR Date                                                                                 7626 non-null   object
 58  SRR Date                                                                                 7626 non-null   object
 59  SMR Date                                                                                 7626 non-null   object
dtypes: int64(17), object(43)
memory usage: 3.5+ MB

In [36]:
df.iloc[:, 60:].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7626 entries, 0 to 7625
Data columns (total 59 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Patient Hospitalization category text                                7626 non-null   object
 1   Patient Hospitalization data availability Code                       7626 non-null   int64
 2   Patient Hospital Readmission Category                                7626 non-null   object
 3   Patient Hospital Readmission data availability Code                  7626 non-null   int64
 4   Patient Survival Category Text                                       7626 non-null   object
 5   Patient Survival data availability code                              7626 non-null   int64
 6   Number of patients included in hospitalization summary               7626 non-null   object
 7   Number of hospitalizations included in hospital readmission summary  7626 non-null   object
 8   Number of patients included in survival summary                      7626 non-null   object
 9   Mortality Rate (Facility)                                            7626 non-null   object
 10  Mortality Rate: Upper Confidence Limit (97.5%)                       7626 non-null   object
 11  Mortality Rate: Lower Confidence Limit (2.5%)                        7626 non-null   object
 12  Readmission Rate (Facility)                                          7626 non-null   object
 13  Readmission Rate: Upper Confidence Limit (97.5%)                     7626 non-null   object
 14  Readmission Rate: Lower Confidence Limit (2.5%)                      7626 non-null   object
 15  Hospitalization Rate (Facility)                                      7626 non-null   object
 16  Hospitalization Rate: Upper Confidence Limit (97.5%)                 7626 non-null   object
 17  Hospitalization Rate: Lower Confidence Limit (2.5%)                  7626 non-null   object
 18  Number of pediatric PD patients with Kt/V data                       7626 non-null   object
 19  Pediatric PD Kt/V Data Availability Code                             7626 non-null   int64
 20  Number of pediatric PD patient-months with KT/V data                 7626 non-null   object
 21  Percentage of pediatric PD patients with Kt/V>=1.8                   7626 non-null   object
 22  SIR Date                                                             7626 non-null   object
 23  Patient Infection Data Availability Code                             7626 non-null   int64
 24  Patient Infection category text                                      7626 non-null   object
 25  Standard Infection Ratio                                             7626 non-null   object
 26  SIR: Upper Confidence Limit (97.5%)                                  7626 non-null   object
 27  SIR: Lower Confidence Limit (2.5%)                                   7626 non-null   object
 28  Transfusion Rate (Facility)                                          7626 non-null   object
 29  Transfusion Rate: Upper Confidence Limit (97.5%)                     7626 non-null   object
 30  Transfusion Rate: Lower Confidence Limit (2.5%)                      7626 non-null   object
 31  Fistula data availability code                                       7626 non-null   int64
 32  Fistula Category Text                                                7626 non-null   object
 33  Number of Patients included in fistula summary                       7626 non-null   object
 34  Fistula Rate (Facility)                                              7626 non-null   object
 35  Fistula Rate: Upper Confidence Limit (97.5%)                         7626 non-null   object
 36  Fistula Rate: Lower Confidence Limit (2.5%)                          7626 non-null   object
 37  Number of patients in long term catheter summary                     7626 non-null   object
 38  Number of patient months in long term catheter summary               7626 non-null   object
 39  Long term catheter Data Availability Code                            7626 non-null   int64
 40  Percentage of Adult patients with long term catheter in use          7626 non-null   object
 41  Number of patients in nPCR summary                                   7626 non-null   object
 42  Number of patient-months in nPCR summary                             7626 non-null   object
 43  nPCR Data Availability Code                                          7626 non-null   int64
 44  Percentage of pediatric HD patients with nPCR                        7626 non-null   object
 45  DATE_SWR                                                             7626 non-null   object
 46  SWR category text                                                    7626 non-null   object
 47  Patient transplant waitlist data availability code                   7626 non-null   int64
 48  95% C.I. (upper limit) for SWR                                       7626 non-null   object
 49  95% C.I. (lower limit) for SWR                                       7626 non-null   object
 50  Number of patients in this facility for SWR                          7626 non-null   object
 51  Standardized First Kidney Transplant Waitlist Ratio                  7626 non-null   object
 52  PPPW category text                                                   7626 non-null   object
 53  Patient prevalent transplant waitlist data availability code         7626 non-null   int64
 54  95% C.I. (upper limit) for PPPW                                      7626 non-null   object
 55  95% C.I. (lower limit) for PPPW                                      7626 non-null   object
 56  Number of patients for PPPW                                          7626 non-null   object
 57  Percentage of Prevalent Patients Waitlisted                          7626 non-null   object
 58  Location                                                             7162 non-null   object
dtypes: int64(10), object(49)
memory usage: 3.4+ MB

In [25]:
df.iloc[:, :30].describe()

,Provider Number,Network,Five Star Data Availability Code,Zip,Late Shift,# of Dialysis Stations,Offers in-center hemodialysis,Offers peritoneal dialysis,Offers home hemodialysis training,HGB<10 data availability code,Hgb > 12 data availability code
count,7626.000000,7626.000000,7626.000000,7626.000000,7626.000000,7626.000000,7626.000000,7626.000000,7626.00000,7626.000000,7626.000000
mean,315876.077105,9.660372,31.525833,50297.359691,0.167060,17.463284,0.940336,0.525439,0.29006,31.839890,31.839890
std,193257.685562,4.708672,83.403249,27581.675445,0.373054,8.495540,0.236879,0.499385,0.45382,75.349864,75.349864
min,12306.000000,1.000000,1.000000,603.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,1.000000
25%,142822.250000,6.000000,1.000000,29533.000000,0.000000,12.000000,1.000000,0.000000,0.00000,1.000000,1.000000
50%,322545.500000,9.000000,1.000000,46032.000000,0.000000,17.000000,1.000000,1.000000,0.00000,1.000000,1.000000
75%,452511.750000,14.000000,1.000000,76060.750000,0.000000,22.000000,1.000000,1.000000,1.00000,1.000000,1.000000
max,852568.000000,18.000000,261.000000,99801.000000,1.000000,80.000000,1.000000,1.000000,1.00000,258.000000,258.000000

In [29]:
df.iloc[:, 30:90].describe()

,Patient Transfusion data availability Code,Adult HD Kt/V data availability code,Adult PD Kt/V Data Availability Code,Pediatric HD Kt/V Data Availability Code,Hypercalcemia Data Availability Code,Serum phosphorus Data Availability Code,Patient Hospitalization data availability Code,Patient Hospital Readmission data availability Code,Patient Survival data availability code,Pediatric PD Kt/V Data Availability Code,Patient Infection Data Availability Code
count,7626.000000,7626.000000,7626.000000,7626.000000,7626.000000,7626.00000,7626.00000,7626.000000,7626.000000,7626.000000,7626.000000
mean,41.090742,26.262392,170.362575,255.115132,13.552190,13.12300,25.68673,26.699449,30.239182,255.840808,41.942958
std,87.672939,70.987742,108.505266,17.913859,52.313945,51.23718,74.10966,74.577879,79.229534,19.258111,88.145757
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,259.000000,1.000000,1.00000,1.00000,1.000000,1.000000,259.000000,1.000000
50%,1.000000,1.000000,201.000000,259.000000,1.000000,1.00000,1.00000,1.000000,1.000000,259.000000,1.000000
75%,1.000000,1.000000,257.000000,259.000000,1.000000,1.00000,1.00000,1.000000,1.000000,259.000000,1.000000
max,258.000000,258.000000,258.000000,259.000000,258.000000,258.00000,258.00000,258.000000,258.000000,259.000000,258.000000

In [30]:
df.iloc[:, 90:].describe()

,Fistula data availability code,Long term catheter Data Availability Code,nPCR Data Availability Code,Patient transplant waitlist data availability code,Patient prevalent transplant waitlist data availability code
count,7626.000000,7626.000000,7626.000000,7626.000000,7626.000000
mean,22.494099,21.936271,254.674928,97.691975,14.793994
std,67.614074,65.879543,20.264866,105.786322,55.649087
min,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,259.000000,1.000000,1.000000
50%,1.000000,1.000000,259.000000,1.000000,1.000000
75%,1.000000,1.000000,259.000000,199.000000,1.000000
max,258.000000,258.000000,259.000000,258.000000,258.000000

In [9]:
df['Five Star'].unique()

array(['2', '3', '5', '4', 'Not Available', '1'], dtype=object)

In [10]:
df[['Profit or Non-Profit','Percentage of Prevalent Patients Waitlisted']]

     Profit or Non-Profit Percentage of Prevalent Patients Waitlisted
0              Non-Profit                                         9.2
1                  Profit                                        20.1
2                  Profit                                        36.4
3                  Profit                                         7.4
4                  Profit                                        14.2
...                   ...                                         ...
7621               Profit                                         9.5
7622               Profit                                          14
7623               Profit                               Not Available
7624               Profit                                         9.2
7625               Profit                                        17.4

[7626 rows x 2 columns]

# Column Names Defined

### Star Rating Explained
The “Dialysis Facility Compare (DFC) Star Program” is a rating system developed by Medicare that assigns 1 to 5 stars to dialysis facilities by comparing the health of the patients in their clinics to the patients in other dialysis facilities across the country.

### Serum phosphorus significance
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

### Concept of Kt/V
The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

### Hgb g/dL
Hemoglobin is a protein in your red blood cells that carries oxygen from your lungs to the rest of your body. A normal hemoglobin level is 11 to 18 grams per deciliter (g/dL), depending on your age and gender. But 7 to 8 g/dL is a safe level.

### Hypercalcemia & Serum Calcium
Hypercalcemia is a condition in which the calcium level in your blood is above normal. Too much calcium in your blood can weaken your bones, create kidney stones, and interfere with how your heart and brain work. Hypercalcemia is usually a result of overactive parathyroid glands.
A normal serum calcium level is 8-10 mg/dL (2-2.5 mmol/L) with some interlaboratory variation in the reference range, and hypercalcemia is defined as a serum calcium level greater than 10.5 mg/dL (>2.5 mmol/L).

### AV fistula
The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

### nPCR
The normalized protein catabolic rate (nPCR) is a formula commonly used to assess dietary protein intake in dialysis patients, as a means towards determining nutritional adequacy, a major problem in many ESRD patients. 
The nPCR is reported in grams of urea nitrogen per kilogram per day.
Most guidelines specify maintaining the protein intake above 1.0 – 1.2 g/kg/day in dialysis patients, with values less than 0.8 g/kg/day being equated with malnutrition.

### Standardized Waitlist Ratio (SWR)
The Standardized Waitlist Ratio (SWR) measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received a living donor transplant within the first year of initiating dialysis. SWR is calculated to compare the observed waitlisting rate in the facility to the waitlisting rate that was expected.

# Preliminary thoughts for data analysis
I'm interested in comparing dialysis star rating to patient health indicators (nPCR, serum calcium, Hgb, Kt/V, serum phosphorus).
Also might be interesting to compare patient health indicators to a center's profit/ non-profit status or whether or not it's a chain buisness. 
Another idea is the relationship between star rating or profit/ non-profit status vs SWR.